@hostname = 192.168.15.1
@port = 3000
@host = {{hostname}}:{{port}}


GET http://{{host}}/ping HTTP/1.1


###
GET http://{{host}}/ HTTP/1.1


###
POST http://{{host}}/wifi HTTP/1.1
Content-Type: application/json

{
    "STAssid": "Biznet",
    "STApassword": "Connecting!ndones1@"
}

###
DELETE  http://{{host}}/restart HTTP/1.1
Content-Type: application/json

{
}

